SOGSystem/SOGSystem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('eigyosystem/', include('eigyosystem.eigyo.urls')),
]

SOGSystem/eigyosystem/eigyo/login/urls.py
from django.urls import path, include
from eigyosystem.eigyo.login import views

urlpatterns = [
    path('', views.logineigyo, name='logineigyo'),  # index
]

SOGSystem/eigyosystem/eigyo/menu/urls.py
from django.urls import path
from eigyosystem.eigyo.menu import views

urlpatterns = [
    # 売上
    path('', views.index, name='index'),  # index
]

SOGSystem/eigyosystem/eigyo/uriage/urls.py
from django.urls import path
from eigyosystem.eigyo.uriage import views

urlpatterns = [

    path('', views.uriage, name='uriage'),  # 売上管理
    # path('eigyosystem/', include('eigyosystem.eigyo.urls')),
    # # 売上
    # path('login/', views.logineigyo, name='logineigyo'),  # index
    # path('test/', views.test, name='test'),  # index
    # # re_path(r'^user/(?P<pk>\d+)/test/$', views.test, name='test'),
    #
    # # 売上
    # path('index/', views.index, name='index'),  # index
    # path('uriage_jisseki/', views.uriage_jisseki, name='uriage_jisseki'),  # 売上実績
    # path('uriage_chart/', views.uriage_chart, name='uriage_chart'),  # 売上実績
    # path('uriage_chart_total/', views.uriage_chart_total, name='uriage_chart_total'),  # 売上実績
    # path('yosan/', views.yosan, name='yosan'),  # 売上管理
    # path('yosan_chart/', views.yosan_chart, name='yosan_chart'),  # 売上実績

]

SOGSystem/eigyosystem/eigyo/urls.py
from django.urls import path, include
from eigyosystem.eigyo.login import views
from eigyosystem.eigyo.menu import views

app_name = 'eigyosystem'
urlpatterns = [
    # 売上
    path('login/', include('eigyosystem.eigyo.login.urls')),  # 登録
    # path('test/', views.test, name='test'),  # index
    # re_path(r'^user/(?P<pk>\d+)/test/$', views.test, name='test'),

    # 売上
    path('index/', include('eigyosystem.eigyo.menu.urls')),  # index
    path('uriage/', include('eigyosystem.eigyo.uriage.urls')),  # 売上管理
    path('yosan/', include('eigyosystem.eigyo.yosan.urls')),  # 売上管理
    # path('uriage_jisseki/', views.uriage_jisseki, name='uriage_jisseki'),  # 売上実績
    # path('uriage_chart/', views.uriage_chart, name='uriage_chart'),  # 売上実績
    # path('uriage_chart_total/', views.uriage_chart_total, name='uriage_chart_total'),  # 売上実績
    # path('yosan_chart/', views.yosan_chart, name='yosan_chart'),  # 売上実績

]

SOGSystem/eigyosystem/eigyo/yosan/urls.py
from django.urls import path
from eigyosystem.eigyo.yosan import views

urlpatterns = [

    path('', views.yosan, name='yosan'),  # 売上管理
    # path('eigyosystem/', include('eigyosystem.eigyo.urls')),
    # # 売上
    # path('login/', views.logineigyo, name='logineigyo'),  # index
    # path('test/', views.test, name='test'),  # index
    # # re_path(r'^user/(?P<pk>\d+)/test/$', views.test, name='test'),
    #
    # # 売上
    # path('index/', views.index, name='index'),  # index
    # path('uriage/', views.uriage, name='uriage'),  # 売上管理
    # path('uriage_jisseki/', views.uriage_jisseki, name='uriage_jisseki'),  # 売上実績
    # path('uriage_chart/', views.uriage_chart, name='uriage_chart'),  # 売上実績
    # path('uriage_chart_total/', views.uriage_chart_total, name='uriage_chart_total'),  # 売上実績
    # path('yosan_chart/', views.yosan_chart, name='yosan_chart'),  # 売上実績

]

SOGSystem/eigyosystem/models.py
from django.db import models

# Create your models here.

SOGSystem/eigyosystem/eigyo/login/forms.py
from django import forms
from django.contrib.auth.models import User
import re


def email_check(email):
    pattern = re.compile(r"\"?([-a-zA-Z0-9.'?{}]+@\w+\.\w+)\"?")
    return re.match(pattern, email)


class LoginForm(forms.Form):
    username = forms.CharField(label='Username', max_length=50)
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    # use clean methods to define custom validation rules

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if email_check(username):
            filter_result = User.objects.filter(email__exact=username)
            if not filter_result:
                raise forms.ValidationError('This email does not exist')
        else:
            filter_result = User.objects.filter(username__exact=username)
            if not filter_result:
                raise forms.ValidationError('This username does not exist Please register first')

        return username

SOGSystem/eigyosystem/eigyo/login/views.py
from django.shortcuts import render
from django.contrib import auth
from django.http import HttpResponseRedirect
from django.urls import reverse
from eigyosystem.eigyo.login.forms import LoginForm


def logineigyo(request):
    if request.method == 'POST':

        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = auth.authenticate(username=username, password=password)
            if user is not None and user.is_active:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('eigyosystem:index'))
            else:
                return render(request, 'login/logineigyo.html',
                              {'form': form, 'message': 'Wrong password Please Try agagin'})
    else:
        form = LoginForm()

    return render(request, 'login/logineigyo.html', {'form': form})


def test(request):

    print('7777777777745564564567456456564')
    return render(request, 'test.html', {'form': 'form'})

SOGSystem/eigyosystem/eigyo/menu/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from eigyosystem.eigyo.menu import viewcommon


@login_required
def index(request):
    indexes = viewcommon.indexview()

    return render(request, 'menu/index.html', {'indexes': indexes})

SOGSystem/eigyosystem/eigyo/uriage/views.py
from django.shortcuts import render


def uriage(request):
    return render(request, 'uriage/uriage.html', {'sales': 'c1'})

SOGSystem/eigyosystem/eigyo/yosan/views.py
from django.shortcuts import render


def yosan(request):
    return render(request, 'yosan/yosan.html', {'sales': 'c1'})

SOGSystem/eigyosystem/views.py
from django.shortcuts import render

# Create your views here.

SOGSystem/eigyosystem/templates/base.html
{% load i18n static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block title %}
        <title>base</title>
    {% endblock %}

    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
    {% block css %}
    {% endblock %}
</head>
<body>
    <div class="container my-con">
        {% block content %}
        {% endblock %}
    </div>

<script src="{% static 'assets/js/jquery.min.js' %}"></script>
<script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

SOGSystem/eigyosystem/templates/login/logineigyo.html
{% extends 'base.html' %}
{% load i18n static %}
{% block title %}<h1 class="my-con1">Login Page</h1>{% endblock %}
{% block css %}
    {#    <link rel="stylesheet" href="{% static '/CSS/login.css' %}">#}
{% endblock %}


{% block content %}
    {% if message %}
        {{ message }}
    {% endif %}
    <div class="form-group">
        <form method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group ">
                    {{ field.errors }}
                    {{ field.label_tag }}{{ field }}
                    {% if field.help_text %}
                        <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                </div>
            {% endfor %}
            <div class="btn">
                <input type="submit" value="Login">
            </div>
        </form>
    </div>

{% endblock %}

SOGSystem/eigyosystem/templates/menu/index.html
{% load i18n static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0,minimum-scale=1.0,user-scalable=no">

    <title>{{ indexes.system_name }}</title>
    <link rel="icon" href="{% static 'images/logo.svg' %}">
    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/Features-Blue.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/Footer-Dark.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}">
</head>

<body>
    <div class="features-blue" style="padding-bottom: 10rem">
        <div class="container-fluid">
            <div class="intro" style="margin-bottom: 0rem;height: 7%;">
                <h1 class="display-4 text-center" style="margin: 0% 0% 0% 0%;margin-bottom: 2rem;padding: 3% 0% 0% 0%;font-size: 3.5rem;color:black;">{{ indexes.title }}</h1>
            </div>
            <ul class="nav nav-tabs" style="color:black;margin: 0% 0% 3% 0%;height: 3%;">
                {% for key, value in indexes.nav.items %}
                    {% if forloop.last %}
                        <li class="nav-item"><a class="nav-link active" style="color:black;background-color:#007bff;border-color:#ffffff" href="{% url key %}">{{ value }}</a></li>
                    {% else %}
                        <li class="nav-item"><a class="nav-link active" style="color:black;background-color:#007bff;border-color:#ffffff" href="{% url key %}">{{ value }}</a></li>
                    {% endif %}
                {% endfor %}
            </ul>
            <div class="row features">
                <div class="col-sm-6 col-md-4 col-xl-6 offset-xl-0 text-center item" style="width: 50%;max-width: 50%;margin: 0% 0% 0% 0%;padding: 0rem 0rem 0rem 0rem;height: 20%;">
                    <a class="btn btn-primary btn-lg" role="button" style="color:black;width: 90%;height: 4.5rem;margin: 0rem 0rem 0rem 0rem;padding: 1rem 0rem 0rem 0rem;" href="{% url 'eigyosystem:yosan' %}">
                        予算管理
                    </a>
                </div>
                <div class="col-sm-6 col-md-4 col-xl-6 offset-xl-0 text-center item" style="width: 50%;max-width: 50%;margin: 0% 0% 0% 0%;padding: 0rem 0rem 0rem 0rem;height: 20%;">
                    <a class="btn btn-primary btn-lg" role="button" style="color:black;width: 90%;height: 4.5rem;margin: 0rem 0rem 0rem 0rem;padding: 1rem 0rem 0rem 0rem;" href="{% url 'eigyosystem:uriage' %}">
                        売上管理
                    </a>
                </div>
                <div class="col-sm-6 col-md-4 col-xl-6 offset-xl-0 text-center item" style="width: 50%;max-width: 50%;margin: 0% 0% 0% 0%;padding: 0rem 0rem 0rem 0rem;height: 20%;">
                    <a class="btn btn-primary btn-lg" role="button" style="color:black;width: 90%;height: 4.5rem;margin: 0rem 0rem 0rem 0rem;padding: 1rem 0rem 0rem 0rem;" href="#">
                        受注管理（開発中）
                    </a>
                </div>
                <div class="col-sm-6 col-md-4 col-xl-6 offset-xl-0 text-center item" style="width: 50%;max-width: 50%;margin: 0% 0% 0% 0%;padding: 0rem 0rem 0rem 0rem;height: 20%;">
                    <a class="btn btn-primary btn-lg" role="button" style="color:black;width: 90%;height: 4.5rem;margin: 0rem 0rem 0rem 0rem;padding: 1rem 0rem 0rem 0rem;" href="#">
                        出荷管理（開発中）
                    </a>
                </div>
                <div class="col-sm-6 col-md-4 col-xl-6 offset-xl-0 text-center item" style="width: 50%;max-width: 50%;margin: 0% 0% 0% 0%;padding: 0rem 0rem 0rem 0rem;height: 20%;">
                    <a class="btn btn-primary btn-lg" role="button" style="color:black;width: 90%;height: 4.5rem;margin: 0rem 0rem 0rem 0rem;padding: 1rem 0rem 0rem 0rem;" href="#">
                        入金管理（開発中）
                    </a>
                </div>
                <div class="col-sm-6 col-md-4 col-xl-6 offset-xl-0 text-center item" style="width: 50%;max-width: 50%;margin: 0% 0% 0% 0%;padding: 0rem 0rem 0rem 0rem;height: 20%;">
                    <a class="btn btn-primary btn-lg" role="button" style="color:black;width: 90%;height: 4.5rem;margin: 0rem 0rem 0rem 0rem;padding: 1rem 0rem 0rem 0rem;" href="#">
                        顧客管理（開発中）
                    </a>
                </div>
                <div class="col-sm-6 col-md-4 col-xl-6 offset-xl-0 text-center item" style="width: 50%;max-width: 50%;margin: 0% 0% 0% 0%;padding: 0rem 0rem 0rem 0rem;height: 20%;">
                    <a class="btn btn-primary btn-lg" role="button" style="color:black;width: 90%;height: 4.5rem;margin: 0rem 0rem 0rem 0rem;padding: 1rem 0rem 0rem 0rem;" href="#">
                        見積管理（開発中）
                    </a>
                </div>
                <div class="col-sm-6 col-md-4 col-xl-6 offset-xl-0 text-center item" style="width: 50%;max-width: 50%;margin: 0% 0% 0% 0%;padding: 0rem 0rem 0rem 0rem;height: 20%;">
                    <a class="btn btn-primary btn-lg" role="button" style="color:black;width: 90%;height: 4.5rem;margin: 0rem 0rem 0rem 0rem;padding: 1rem 0rem 0rem 0rem;" href="#">
                        案件管理（開発中）
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-dark">
        <footer>
            <div class="container">
                <div class="row" style="height: 103px;">
                    <div class="col-sm-6 col-md-3 item" style="height: 103px;">
                        <img src="{% static 'images/logo.svg' %}" >
                    </div>
                    <div class="col-md-6 col-xl-8 offset-xl-1 item text">
                        <h3>株式会社　住田光学ガラス<br></h3>
                        <p>〒330-8565 埼玉県さいたま市浦和区針ヶ谷4-7-25<br>TEL：<a href="tel:0488323165">048-832-3165</a>　</p>
                        <p>E-MAIL :&nbsp;<a href="mailto:contact-sumita@sumita-opt.co.jp">contact-sumita@sumita-opt.co.jp</a><br></p>
                    </div>
                </div>
                <p class="text-right text-sm-right text-md-right text-lg-right text-xl-right copyright">© 1996 SUMITA OPTICAL GLASS, Inc.<br></p>
            </div>
        </footer>
    </div>
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
</body>

</html>

SOGSystem/eigyosystem/templates/test.html
{% extends 'base.html' %}
{% load i18n static %}
{% block title %}<h1 class="my-con1">aaaaaaaaaaaaa</h1>{% endblock %}
{% block css %}
    {#    <link rel="stylesheet" href="{% static '/CSS/login.css' %}">#}
{% endblock %}


{% block content %}

    aaaaaaaaaaaaaaaaaaaa

{% endblock %}

SOGSystem/eigyosystem/templates/uriage/uriage.html
{% load i18n static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0,minimum-scale=1.0,user-scalable=no">

    <title>営業管理システム</title>
    <link rel="icon" href="{% static 'images/logo.svg' %}">
    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/Features-Blue.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/Footer-Dark.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}">
</head>

<body>
    <div class="features-blue" style="padding-bottom: 22.5rem;">
        <div class="container-fluid">
            <div class="intro" style="margin-bottom: 0rem;height: 7%;">
                <h1 class="display-4 text-center" style="color:black;margin: 0% 0% 0% 0%;margin-bottom: 2rem;padding: 3% 0% 0% 0%;font-size: 3.5rem;">売上管理</h1>
            </div>
            <ul class="nav nav-tabs" style="margin: 0% 0% 3% 0%;height: 3%;">
                <li class="nav-item"><a class="nav-link" style="color:black;border-color:#007bff" href="{% url 'eigyosystem:index' %}">営業管理システム</a></li>
                <li class="nav-item"><a class="nav-link active" style="color:black;background-color:#007bff;border-color:#ffffff" href="{% url 'eigyosystem:uriage' %}">売上管理</a></li>
            </ul>
            <div class="row features">
                <div class="col-sm-6 col-md-4 col-xl-6 offset-xl-0 text-center item" style="width: 50%;max-width: 50%;margin: 0% 0% 0% 0%;padding: 0rem 0rem 0rem 0rem;height: 20%;">
                    <a class="btn btn-primary btn-lg" role="button" style="color:black;width: 90%;height: 4.5rem;margin: 0rem 0rem 0rem 0rem;padding: 1rem 0rem 0rem 0rem;" href="#">
                        売上実績
                    </a>
                </div>
                <div class="col-sm-6 col-md-4 col-xl-6 offset-xl-0 text-center item" style="width: 50%;max-width: 50%;margin: 0% 0% 0% 0%;padding: 0rem 0rem 0rem 0rem;height: 20%;">
                    <a class="btn btn-primary btn-lg" role="button" style="color:black;width: 90%;height: 4.5rem;margin: 0rem 0rem 0rem 0rem;padding: 1rem 0rem 0rem 0rem;" href="#">
                        月別売上（開発中）
                    </a>
                </div>
                <div class="col-sm-6 col-md-4 col-xl-6 offset-xl-0 text-center item" style="width: 50%;max-width: 50%;margin: 0% 0% 0% 0%;padding: 0rem 0rem 0rem 0rem;height: 20%;">
                    <a class="btn btn-primary btn-lg" role="button" style="color:black;width: 90%;height: 4.5rem;margin: 0rem 0rem 0rem 0rem;padding: 1rem 0rem 0rem 0rem;" href="#">
                        顧客別売上（開発中）
                    </a>
                </div>
                <div class="col-sm-6 col-md-4 col-xl-6 offset-xl-0 text-center item" style="width: 50%;max-width: 50%;margin: 0% 0% 0% 0%;padding: 0rem 0rem 0rem 0rem;height: 20%;">
                    <a class="btn btn-primary btn-lg" role="button" style="color:black;width: 90%;height: 4.5rem;margin: 0rem 0rem 0rem 0rem;padding: 1rem 0rem 0rem 0rem;" href="#">
                        製品別売上（開発中）
                    </a>
                </div>
                <div class="col-sm-6 col-md-4 col-xl-6 offset-xl-0 text-center item" style="width: 50%;max-width: 50%;margin: 0% 0% 0% 0%;padding: 0rem 0rem 0rem 0rem;height: 20%;">
                    <a class="btn btn-primary btn-lg" role="button" style="color:black;width: 90%;height: 4.5rem;margin: 0rem 0rem 0rem 0rem;padding: 1rem 0rem 0rem 0rem;" href="#">
                        グラフ表示
                    </a>
                </div>
                <div class="col-sm-6 col-md-4 col-xl-6 offset-xl-0 text-center item" style="width: 50%;max-width: 50%;margin: 0% 0% 0% 0%;padding: 0rem 0rem 0rem 0rem;height: 20%;">
                    <a class="btn btn-primary btn-lg" role="button" style="color:black;width: 90%;height: 4.5rem;margin: 0rem 0rem 0rem 0rem;padding: 1rem 0rem 0rem 0rem;" href="#">
                        製品別売上（開発中）
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-dark">
        <footer>
            <div class="container">
                <div class="row" style="height: 103px;">
                    <div class="col-sm-6 col-md-3 item" style="height: 103px;">
                        <img src="{% static 'images/logo.svg' %}" >
                    </div>
                    <div class="col-md-6 col-xl-8 offset-xl-1 item text">
                        <h3>株式会社　住田光学ガラス<br></h3>
                        <p>〒330-8565 埼玉県さいたま市浦和区針ヶ谷4-7-25<br>TEL：<a href="tel:0488323165">048-832-3165</a>　</p>
                        <p>E-MAIL :&nbsp;<a href="mailto:contact-sumita@sumita-opt.co.jp">contact-sumita@sumita-opt.co.jp</a><br></p>
                    </div>
                </div>
                <p class="text-right text-sm-right text-md-right text-lg-right text-xl-right copyright">© 1996 SUMITA OPTICAL GLASS, Inc.<br></p>
            </div>
        </footer>
    </div>
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
</body>

</html>

SOGSystem/eigyosystem/templates/yosan/yosan.html
{% load i18n static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0,minimum-scale=1.0,user-scalable=no">

    <title>営業管理システム</title>
    <link rel="icon" href="{% static 'images/logo.svg' %}">
    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/Features-Blue.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/Footer-Dark.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}">
</head>

<body>
    <div class="features-blue" style="padding-bottom: 22.5rem;">
        <div class="container-fluid">
            <div class="intro" style="margin-bottom: 0rem;height: 7%;">
                <h1 class="display-4 text-center" style="color:black;margin: 0% 0% 0% 0%;margin-bottom: 2rem;padding: 3% 0% 0% 0%;font-size: 3.5rem;">予算管理</h1>
            </div>
            <ul class="nav nav-tabs" style="margin: 0% 0% 3% 0%;height: 3%;">
                <li class="nav-item"><a class="nav-link" style="color:black;border-color:#007bff" href="{% url 'eigyosystem:index' %}">営業管理システム</a></li>
                <li class="nav-item"><a class="nav-link active" style="color:black;background-color:#007bff;border-color:#ffffff" href="{% url 'eigyosystem:yosan' %}">予算管理</a></li>
            </ul>
            <div class="row features">
                <div class="col-sm-6 col-md-4 col-xl-6 offset-xl-0 text-center item" style="width: 50%;max-width: 50%;margin: 0% 0% 0% 0%;padding: 0rem 0rem 0rem 0rem;height: 20%;">
                    <a class="btn btn-primary btn-lg" role="button" style="color:black;width: 90%;height: 4.5rem;margin: 0rem 0rem 0rem 0rem;padding: 1rem 0rem 0rem 0rem;" href="#">
                        予算登録（開発中）
                    </a>
                </div>
                <div class="col-sm-6 col-md-4 col-xl-6 offset-xl-0 text-center item" style="width: 50%;max-width: 50%;margin: 0% 0% 0% 0%;padding: 0rem 0rem 0rem 0rem;height: 20%;">
                    <a class="btn btn-primary btn-lg" role="button" style="color:black;width: 90%;height: 4.5rem;margin: 0rem 0rem 0rem 0rem;padding: 1rem 0rem 0rem 0rem;" href="#">
                        予算変更（開発中）
                    </a>
                </div>
                <div class="col-sm-6 col-md-4 col-xl-6 offset-xl-0 text-center item" style="width: 50%;max-width: 50%;margin: 0% 0% 0% 0%;padding: 0rem 0rem 0rem 0rem;height: 20%;">
                    <a class="btn btn-primary btn-lg" role="button" style="color:black;width: 90%;height: 4.5rem;margin: 0rem 0rem 0rem 0rem;padding: 1rem 0rem 0rem 0rem;" href="#">
                        予算検索（開発中）
                    </a>
                </div>
                <div class="col-sm-6 col-md-4 col-xl-6 offset-xl-0 text-center item" style="width: 50%;max-width: 50%;margin: 0% 0% 0% 0%;padding: 0rem 0rem 0rem 0rem;height: 20%;">
                    <a class="btn btn-primary btn-lg" role="button" style="color:black;width: 90%;height: 4.5rem;margin: 0rem 0rem 0rem 0rem;padding: 1rem 0rem 0rem 0rem;" href="#">
                        予算グラフ
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-dark">
        <footer>
            <div class="container">
                <div class="row" style="height: 103px;">
                    <div class="col-sm-6 col-md-3 item" style="height: 103px;">
                        <img src="{% static 'images/logo.svg' %}" >
                    </div>
                    <div class="col-md-6 col-xl-8 offset-xl-1 item text">
                        <h3>株式会社　住田光学ガラス<br></h3>
                        <p>〒330-8565 埼玉県さいたま市浦和区針ヶ谷4-7-25<br>TEL：<a href="tel:0488323165">048-832-3165</a>　</p>
                        <p>E-MAIL :&nbsp;<a href="mailto:contact-sumita@sumita-opt.co.jp">contact-sumita@sumita-opt.co.jp</a><br></p>
                    </div>
                </div>
                <p class="text-right text-sm-right text-md-right text-lg-right text-xl-right copyright">© 1996 SUMITA OPTICAL GLASS, Inc.<br></p>
            </div>
        </footer>
    </div>
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
</body>

</html>